server:
   port: 9001

zuul:
    routes:
      spring-cloud-provider:
        path: /provider/**
        serviceId: spring-cloud-provider
      spring-cloud-customer:
        path: /customer/**
        serviceId: spring-cloud-customer
    host:
        connect-timeout-millis: 6000
    retryable: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 2
  MaxAutoRetriesNextServer: 2

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/


